# Copyright (c) 2025 â€” 2026 Ian Torres <iantorres@outlook.com>.
# All rights reserved.

name: Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [ "1.90.0" ]
        variant: [ debug, release ]
        type: [ static, shared ]
        platform: [ linux/amd64, linux/arm64 ]

    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-22.04-arm' || 'ubuntu-latest' }}

    container:
      image: ghcr.io/distributedengine/builder:${{ matrix.version }}-${{ matrix.variant }}-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.variant }} -DBUILD_PROTOCOL_TESTS=ON -DBUILD_PROTOCOL_BENCHMARK=ON
          make -j4
          ctest  --output-on-failure --verbose
          cd ..
          gcovr --print-summary --sort-percentage

      - name: Run benchmarks
        run: |
          ./build/engine-protocol-benchmarks