# Copyright (c) 2025 â€” 2026 Ian Torres <iantorres@outlook.com>.
# All rights reserved.

name: Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [ "1.90.0" ]
        variant: [ debug, release ]
        type: [ static, shared ]

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/distributedengine/builder:${{ matrix.version }}-${{ matrix.variant }}-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          mkdir -p build
          cd build
          if [ "${{ matrix.variant }}" = "debug" ]; then
              BUILD_CONTRACTS=ON
          else
              BUILD_CONTRACTS=OFF
          fi
          
          if [ "${{ matrix.type }}" = "static" ]; then
              BUILD_STATIC=ON
          else
              BUILD_STATIC=OFF
          fi
          
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.variant }} \
                   -DBUILD_PROTOCOL_TESTS=ON \
                   -DBUILD_PROTOCOL_BENCHMARK=ON \
                   -DBUILD_CONTRACTS=${BUILD_CONTRACTS} \
                   -DBUILD_STATIC=${BUILD_STATIC}
          make -j4
          ctest  --output-on-failure --verbose
          cd ..
          gcovr --filter='include/' --print-summary --sort-percentage

      - name: Run benchmarks
        run: |
          ./build/engine-protocol-benchmarks